# Generated by Django 5.2.8 on 2025-12-04 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_jwt_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
